require: rubocop-rails

AllCops:
  # Rubyのバージョンを指定
  TargetRubyVersion: 2.6.5
  # 除外するファイル
  Exclude:
    - vendor/bundle/**/*
    - bin/*
    - db/**/*
    - config/**/*
    - Gemfile
    - node_modules/**/*

# Missing magic comment # frozen_string_literal: true. を無視
Style/FrozenStringLiteralComment:
  Enabled: false

# Missing top-level class documentation comment. を無視
Style/Documentation:
  Enabled: false

# Line is too long を無視
Metrics/LineLength:
  Enabled: false

# Use nested module/class definitions instead of compact style. を無視
Style/ClassAndModuleChildren:
  Enabled: false

# 英語以外のコメントアウトの許容
Style/AsciiComments:
  Enabled: false

#一つのブロックあたりの25行制限を解除
Metrics/BlockLength:
  Exclude:
    - 'spec/requests/api/v1/**'

#find_by_系メソッドの使用を許可
Rails/DynamicFindBy:
  Whitelist:
    - find_by_weather_forecasts

#行数の制限を10から11に変更
Metrics/MethodLength:
  Max: 11

#AbcSizeを15から28に変更
Metrics/AbcSize:
  Max: 28

